version: 2

sources:
    - name: RDS
      database: PAGILA_INC
      freshness:
        warn_after: {count: 12, period: hour}
      loaded_at_field: _fivetran_synced
      schema: NORTHWINDS_RDS_PUBLIC
      tables:
        - name: CUSTOMERS
          freshness:
            error_after: {count: 6, period: hour}
        - name: SUPPLIERS

