version: 2

sources:
    - name: HUBSPOT
      database: PAGILA_INC
      freshness:
        warn_after: {count: 12, period: hour}
      loaded_at_field: _fivetran_synced
      schema: DBT_AZIMMERMAN
      tables:
        - name: CONTACTS
          freshness:
            error_after: {count: 6, period: hour}
        